const Icons = {
    article: "far fa-newspaper",
    podcast: "fas fa-podcast",
    video: "fas fa-tv",
    list: "fas fa-file-alt",
    book: "fas fa-book-open",
    game: "fas fa-gamepad",
    service: "fas fa-server",
    lecture: "fas fa-chalkboard-teacher",
    quote: "fas fa-comment",
    tool: "fas fa-wrench",
    music: "fas fa-music",
    image: "fas fa-image",
    encyclopedia: "fas fa-globe",
    term: "fas fa-ribbon",
    note: "fas fa-sticky-note",
    inspiration: "fas fa-star",
    date: "fas fa-clock",
    author: "fas fa-user",
    tags: "fas fa-tag",
    project: "fas fa-leaf",
    progress: "fas fa-clock",
    file: "fas fa-folder-open",
    dash: "fas fa-caret-right",
    link: "fas fa-link",
    true: "fas fa-check",
    false: "fas fa-times",
  };